version: "3"

services:
  nats:
    image: 'nats:latest'
    entrypoint: "/gnatsd -DV"
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server
  sentiment-service:
    build:
      context: "./sentimentservice"
    entrypoint: /go/sentiment-service
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
  user-service:
    build:
      context: "./userservice"
    entrypoint: /go/user-service
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
  server-tweet:
    build:
      context: "./tweet-server"
    entrypoint: /go/twitter-server
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
  frontend:
    build:
      context: "./frontendservice"
    entrypoint: /go/front-end
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
    ports:
      - "3000:3000"



