version: "3"

services:
  nats:
    image: 'nats:latest'
    entrypoint: "/gnatsd -DV"
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server
  user-service:
    build:
      context: "./userservice"
    entrypoint: /go/user-service
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
  server:
    build:
      context: "./server"
    entrypoint: /go/server
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
  frontend:
    build:
      context: "./frontendservice"
    entrypoint: /go/front-end
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
    ports:
      - "3000:3000"



