version: "3"
services:
  nats:
    image: 'nats:latest'
    entrypoint: "/gnatsd -DV"
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server
  sentiment-service:
    build:
      context: "./sentimentservice"
    image: bricov/sentiment_sentimentservice
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
  server-tweet:
    build:
      context: "./twitter-server"
    image: bricov/sentiment_server
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
  hacker-news:
    build:
      context: "./hackernewsservice"
    image: bricov/sentiment_hackernews
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
  frontend:
    build:
      context: "./frontendservice"
    image: bricov/sentiment_frontend
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
    ports:
      - "3000:3000"
  repository:
    build:
      context: "./repository"
    image: bricov/sentiment_repository
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
    ports:
      - "9090:9090"
  mongodb:
    image: mongo:3.6.1
    container_name: sentiment-mongodb
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"
    command: mongod
volumes:
  mongodb:
  mongodb_config:






