version: "3"
services:
  nats:
    image: 'nats:latest'
    entrypoint: "/gnatsd -DV"
    expose:
      - "4222"
    ports:
      - "8222:8222"
  sentiment-service:
    build:
      context: "./sentimentservice"
    image: bricov/sentiment_sentimentservice
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
  server-tweet:
    build:
      context: "./twitter-server"
    image: bricov/sentiment_server
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
  hacker-news:
    build:
      context: "./hackernewsservice"
    image: bricov/sentiment_hackernews
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
  frontend:
    build:
      context: "./frontendservice"
    ports:
      - "80:80"
    image: bricov/sentiment_frontend
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
  repository:
    build:
      context: "./repository"
    image: bricov/sentiment_repository
    links:
      - mongodb-repository
    environment:
      DATASTORE_ADDR: datastore:27017
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
    ports:
      - "9090:9090"
  mongodb-repository:
    image: mongo:latest
    ports:
      - 27017:27017







