version: "2"

services:
  nats:
    image: 'nats:latest'
    entrypoint: "/gnatsd -DV"
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server
  twitter-service:
      build:
        context: "./twitterservice"
      entrypoint: /go/twitter-service
      links:
        - nats
      environment:
        - "NATS_URI=nats://nats:4222"
      depends_on:
        - nats
  frontend:
    build:
      context: "./frontend"
    entrypoint: /go/frontend
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
    ports:
      - "3000:3000"
