version: "3"

services:
  nats:
    image: 'nats:latest'
    entrypoint: "/gnatsd -DV"
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server

  sentiment-service:
    build:
      context: "./sentimentservice"
    entrypoint: /go/sentiment-service
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats

# Comment / Uncomment one these two twitter streaming options

#  Streaming option using git@github.com:dghubble/go-twitter.git
#  server:
#    build:
#      context: "./server"
#    entrypoint: /go/server
#    links:
#      - nats
#    environment:
#      - "NATS_URI=nats://nats:4222"
#    depends_on:
#      - nats

#  Streaming option using github.com/ChimeraCoder/anaconda
  server-tweet:
    build:
      context: "./tweet-server"
    entrypoint: /go/twitter-server
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats

  hacker-news:
    build:
      context: "./hackernewsservice"
    entrypoint: /go/hackernews-service
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats

# end streaming options

  frontend:
    build:
      context: "./frontendservice"
    entrypoint: /go/front-end
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
    ports:
      - "3000:3000"



