apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: frontendservice
  name: frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontendservice
    spec:
      containers:
      - env:
        image: bricov/sentiment_frontend
        name: frontend
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}