apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.13.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
        - name: NATS_URI
          value: nats://nats:4222
        image: bricov/sentiment_frontend
        name: frontend
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
