apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-repository
  name: mongodb-repository
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-repository
    spec:
      containers:
      - image: mongo:latest
        name: mongodb-repository
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
