apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
      - args:
        - mongod
        image: mongo:3.6.1
        name: sentiment-mongodb
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodb
        - mountPath: /data/configdb
          name: mongodb-config
      restartPolicy: Always
      volumes:
      - name: mongodb
        persistentVolumeClaim:
          claimName: mongodb
      - name: mongodb-config
        persistentVolumeClaim:
          claimName: mongodb-config
status: {}
