apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: repository
  name: repository
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: repository
    spec:
      containers:
      - env:
        - name: NATS_URI
          value: nats://nats:4222
        image: bricov/sentiment_repository
        name: repository
        ports:
        - containerPort: 9090
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources: {}
status: {}
