apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.13.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: sentiment-service
  name: sentiment-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sentiment-service
    spec:
      containers:
      - env:
        - name: NATS_URI
          value: nats://nats:4222
        image: bricov/sentiment_sentimentservice
        name: sentiment-service
        resources: {}
      restartPolicy: Always
status: {}
