apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: server-tweet
  name: server-tweet
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: server-tweet
    spec:
      containers:
      - env:
        - name: NATS_URI
          value: nats://nats:4222
        image: bricov/sentiment_server
        name: server-tweet
        resources: {}
      restartPolicy: Always
status: {}
