// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hackernews.proto

/*
Package Transport is a generated protocol buffer package.

It is generated from these files:
	hackernews.proto
	sentiment.proto
	tweettwit.proto
	twitter.proto

It has these top-level messages:
	HackerNews
	Sentiment
	TweetTwitter
	Tweet
*/
package Transport

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HackerNews struct {
	News []string `protobuf:"bytes,1,rep,name=News" json:"News,omitempty"`
}

func (m *HackerNews) Reset()                    { *m = HackerNews{} }
func (m *HackerNews) String() string            { return proto.CompactTextString(m) }
func (*HackerNews) ProtoMessage()               {}
func (*HackerNews) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HackerNews) GetNews() []string {
	if m != nil {
		return m.News
	}
	return nil
}

func init() {
	proto.RegisterType((*HackerNews)(nil), "Transport.HackerNews")
}

func init() { proto.RegisterFile("hackernews.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 83 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x48, 0x4c, 0xce,
	0x4e, 0x2d, 0xca, 0x4b, 0x2d, 0x2f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x0c, 0x29,
	0x4a, 0xcc, 0x2b, 0x2e, 0xc8, 0x2f, 0x2a, 0x51, 0x52, 0xe0, 0xe2, 0xf2, 0x00, 0x4b, 0xfb, 0xa5,
	0x96, 0x17, 0x0b, 0x09, 0x71, 0xb1, 0x80, 0x68, 0x09, 0x46, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x30,
	0x3b, 0x89, 0x0d, 0xac, 0xc7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x49, 0xc6, 0x2a, 0xe9, 0x47,
	0x00, 0x00, 0x00,
}
